version: '3.8'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: printstat
      POSTGRES_PASSWORD: printstat
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  daemon:
    image: nicotechru/printstat-daemon
    container_name: daemon
    restart: always
    env_file:
      - ./daemon/daemon.env
    ports:
      - 8081:8080
    volumes:
      - ./daemon/data:/printstat/daemon
    depends_on:
      - db
  agent:
    image: nicotechru/printstat-agent
    container_name: agent
    restart: always
    env_file:
      - ./agent/agent.env
    volumes:
      - /root/.ssh:/root/.ssh
      - ./agent/data:/printstat/agent
    network_mode: host
    depends_on:
      - daemon
  webgui:
    image: nicotechru/printstat-webgui
    container_name: webgui
    restart: always
    environment:
      API_URL: http://vm-printstat.nicotech.ru/daemon
      WS_URL: ws://vm-printstat.nicotech.ru/daemon/websocket
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/ssl/:/etc/ssl/nicotech.ru/
    depends_on:
      - daemon
      - agent
